name: "RPL-2023-CICD Demo"
on:
  push:
    branches:
    - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Do python linter test check
      run: |
        sudo apt install python3-pip -y
        python -m pip install pylint
        pip install flask
        pylint app.py --disable=C0114,C0116
    - name: create folder for copying file
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: 3.138.116.132
        username: rplcicd
        password: rplcicd2023
        port: 22
        script: mkdir -p /home/rplcicd/13521106/
    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: 3.138.116.132
        username: rplcicd
        password: rplcicd2023
        port: 22
        source: "app.py"
        target: "/home/rplcicd/13521106/"
    - name: kill existing flask app
      continue-on-error: true
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: 3.138.116.132
        username: rplcicd
        password: rplcicd2023
        port: 22
        script: pkill -f 12043
    - name: start flask app
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: 3.138.116.132
        username: rplcicd
        password: rplcicd2023
        port: 22
        script: cd /home/rplcicd/13521106/ && screen -dmS flask-12043 python3 -m flask run --host=0.0.0.0 --port=12043 && ps -ef | grep 12043